version: '2'
services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres

  odoo12:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8099:8069"
    tty: true
    #command: -u pycon -d pycon
    #command: odoo scaffold /mnt/extra-addons/pycon
    volumes:
      - ./extra-addons:/mnt/extra-addons
      - ./etc:/etc/odoo
